---
- hosts: all
  gather_facts: no

  tasks:

    - name: Delete keypair
      ec2_key:  
        name: "{{ name }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: absent
      ignore_errors: True