- hosts: all
  gather_facts: no
  tasks:
    - name: "Create simple deployment on Kubernetes"
      community.kubernetes.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        definition: "{{ definition }}"