- hosts: all
  gather_facts: no
  tasks:
    - name: "Delete deployment"
      community.kubernetes.k8s:
        state: absent
        kubeconfig: "{{ kubeconfig }}"
        definition: "{{ definition }}"