---
- name: Check job in torque
  import_playbook: check_torque.yml
  when: scheduler == "torque"

- name: Check job in slurm
  import_playbook: check_slurm.yml
  when: scheduler == "slurm"

# # TODO: playbook for batch
# - name: Check job in any compute
#   import_playbook: check_batch.yml
#   when: scheduler == "batch"