---
- name: Start job in torque
  import_playbook: start_torque.yml
  when: scheduler == "torque"

- name: Start job in slurm
  import_playbook: start_slurm.yml
  when: scheduler == "slurm"

# # TODO: playbook for batch
# - name: Start job in any compute
#   import_playbook: start_batch.yml
#   when: scheduler == "batch"