---
- hosts: all
  become_user: root
  become: yes
  vars:
    pip_install_packages:
      - name: cryptography
        version: "3.3"
      - name: pyOpenSSL

  tasks:
    - name: Generate OpenStack key
      block:
        - set_fact:
            key_name: "{{ public_ipv4_address | replace('.','-') }}-xOpera"
            ssh_path: "/root/.ssh/"
        - file:
            path: "{{ ssh_path }}"
            state: directory
        - openssl_privatekey:
            path: "{{ ssh_path }}{{ key_name }}"
            size: 4096
        - openssl_publickey:
            path: "{{ ssh_path }}{{ key_name }}.pubk"
            format: OpenSSH
            privatekey_path: "{{ ssh_path }}{{ key_name }}"
        - slurp:
            src: "{{ ssh_path }}{{ key_name }}.pubk"
          register: key
        - authorized_key:
            user: "{{ ansible_user }}"
            state: present
            key: '{{ key.content | b64decode }}'

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_distribution == "CentOS"
    - role: geerlingguy.pip